// Code generated by protoc-gen-go. DO NOT EDIT.
// source: projTags.proto

package projTags

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProjTagsRequest struct {
	ProjUrl              []string `protobuf:"bytes,1,rep,name=ProjUrl,proto3" json:"ProjUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjTagsRequest) Reset()         { *m = ProjTagsRequest{} }
func (m *ProjTagsRequest) String() string { return proto.CompactTextString(m) }
func (*ProjTagsRequest) ProtoMessage()    {}
func (*ProjTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5516a5a2d60266, []int{0}
}

func (m *ProjTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjTagsRequest.Unmarshal(m, b)
}
func (m *ProjTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjTagsRequest.Marshal(b, m, deterministic)
}
func (m *ProjTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjTagsRequest.Merge(m, src)
}
func (m *ProjTagsRequest) XXX_Size() int {
	return xxx_messageInfo_ProjTagsRequest.Size(m)
}
func (m *ProjTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjTagsRequest proto.InternalMessageInfo

func (m *ProjTagsRequest) GetProjUrl() []string {
	if m != nil {
		return m.ProjUrl
	}
	return nil
}

type TagList struct {
	ProjectName          string   `protobuf:"bytes,1,opt,name=ProjectName,proto3" json:"ProjectName,omitempty"`
	Tags                 []string `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagList) Reset()         { *m = TagList{} }
func (m *TagList) String() string { return proto.CompactTextString(m) }
func (*TagList) ProtoMessage()    {}
func (*TagList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5516a5a2d60266, []int{1}
}

func (m *TagList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagList.Unmarshal(m, b)
}
func (m *TagList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagList.Marshal(b, m, deterministic)
}
func (m *TagList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagList.Merge(m, src)
}
func (m *TagList) XXX_Size() int {
	return xxx_messageInfo_TagList.Size(m)
}
func (m *TagList) XXX_DiscardUnknown() {
	xxx_messageInfo_TagList.DiscardUnknown(m)
}

var xxx_messageInfo_TagList proto.InternalMessageInfo

func (m *TagList) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *TagList) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ProjTagsResponse struct {
	TagsList             []*TagList `protobuf:"bytes,1,rep,name=TagsList,proto3" json:"TagsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjTagsResponse) Reset()         { *m = ProjTagsResponse{} }
func (m *ProjTagsResponse) String() string { return proto.CompactTextString(m) }
func (*ProjTagsResponse) ProtoMessage()    {}
func (*ProjTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5516a5a2d60266, []int{2}
}

func (m *ProjTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjTagsResponse.Unmarshal(m, b)
}
func (m *ProjTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjTagsResponse.Marshal(b, m, deterministic)
}
func (m *ProjTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjTagsResponse.Merge(m, src)
}
func (m *ProjTagsResponse) XXX_Size() int {
	return xxx_messageInfo_ProjTagsResponse.Size(m)
}
func (m *ProjTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjTagsResponse proto.InternalMessageInfo

func (m *ProjTagsResponse) GetTagsList() []*TagList {
	if m != nil {
		return m.TagsList
	}
	return nil
}

func init() {
	proto.RegisterType((*ProjTagsRequest)(nil), "ProjTagsRequest")
	proto.RegisterType((*TagList)(nil), "TagList")
	proto.RegisterType((*ProjTagsResponse)(nil), "ProjTagsResponse")
}

func init() { proto.RegisterFile("projTags.proto", fileDescriptor_2a5516a5a2d60266) }

var fileDescriptor_2a5516a5a2d60266 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0xcf,
	0x0a, 0x49, 0x4c, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe6, 0xe2, 0x0f, 0x80,
	0x8a, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x83, 0x84, 0x42, 0x8b,
	0x72, 0x24, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x25, 0x7b, 0x2e, 0xf6, 0x90, 0xc4,
	0x74, 0x9f, 0xcc, 0xe2, 0x12, 0x21, 0x05, 0x2e, 0x6e, 0x90, 0x68, 0x6a, 0x72, 0x89, 0x5f, 0x62,
	0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0xb2, 0x90, 0x90, 0x10, 0x17, 0x0b, 0xc8,
	0x54, 0x09, 0x26, 0xb0, 0x19, 0x60, 0xb6, 0x92, 0x05, 0x97, 0x00, 0xc2, 0xb6, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x15, 0x2e, 0x0e, 0x10, 0x1f, 0x64, 0x2a, 0xd8, 0x3e, 0x6e, 0x23, 0x0e,
	0x3d, 0xa8, 0x2d, 0x41, 0x70, 0x19, 0x23, 0x07, 0x2e, 0x0e, 0x98, 0x4e, 0x21, 0x13, 0x2e, 0x6e,
	0xf7, 0xd4, 0x12, 0x38, 0x57, 0x40, 0x0f, 0xcd, 0x07, 0x52, 0x82, 0x7a, 0xe8, 0xb6, 0x28, 0x31,
	0x24, 0xb1, 0x81, 0x3d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xe8, 0x4c, 0x19, 0x02,
	0x01, 0x00, 0x00,
}
