// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: projTags.proto

package projTags

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProjTags service

type ProjTagsService interface {
	GetProjTags(ctx context.Context, in *ProjTagsRequest, opts ...client.CallOption) (*ProjTagsResponse, error)
}

type projTagsService struct {
	c    client.Client
	name string
}

func NewProjTagsService(name string, c client.Client) ProjTagsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "projtags"
	}
	return &projTagsService{
		c:    c,
		name: name,
	}
}

func (c *projTagsService) GetProjTags(ctx context.Context, in *ProjTagsRequest, opts ...client.CallOption) (*ProjTagsResponse, error) {
	req := c.c.NewRequest(c.name, "ProjTags.GetProjTags", in)
	out := new(ProjTagsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProjTags service

type ProjTagsHandler interface {
	GetProjTags(context.Context, *ProjTagsRequest, *ProjTagsResponse) error
}

func RegisterProjTagsHandler(s server.Server, hdlr ProjTagsHandler, opts ...server.HandlerOption) error {
	type projTags interface {
		GetProjTags(ctx context.Context, in *ProjTagsRequest, out *ProjTagsResponse) error
	}
	type ProjTags struct {
		projTags
	}
	h := &projTagsHandler{hdlr}
	return s.Handle(s.NewHandler(&ProjTags{h}, opts...))
}

type projTagsHandler struct {
	ProjTagsHandler
}

func (h *projTagsHandler) GetProjTags(ctx context.Context, in *ProjTagsRequest, out *ProjTagsResponse) error {
	return h.ProjTagsHandler.GetProjTags(ctx, in, out)
}
